# blocks/Training/training_functions.py
# 학습 및 검증 함수들

def generate_training_functions_snippet():
    """
    학습 및 검증 함수들 생성
    """
    lines = []
    lines.append("# 학습 함수")
    lines.append("def train_epoch(model, loader, criterion, optimizer):")
    lines.append("    \"\"\"한 에폭 학습\"\"\"")
    lines.append("    model.train()")
    lines.append("    total_loss = 0")
    lines.append("    correct = 0")
    lines.append("    total = 0")
    lines.append("    ")
    lines.append("    progress_bar = tqdm(loader, desc='Training', ncols=100)")
    lines.append("    for batch_idx, (data, target) in enumerate(progress_bar):")
    lines.append("        data, target = data.to(device), target.to(device)")
    lines.append("        ")
    lines.append("        # 순전파")
    lines.append("        optimizer.zero_grad()")
    lines.append("        output = model(data)")
    lines.append("        loss = criterion(output, target)")
    lines.append("        ")
    lines.append("        # 역전파")
    lines.append("        loss.backward()")
    lines.append("        optimizer.step()")
    lines.append("        ")
    lines.append("        # 통계")
    lines.append("        total_loss += loss.item()")
    lines.append("        pred = output.argmax(dim=1, keepdim=True)")
    lines.append("        correct += pred.eq(target.view_as(pred)).sum().item()")
    lines.append("        total += target.size(0)")
    lines.append("        ")
    lines.append("        # 진행 상황 업데이트")
    lines.append("        progress_bar.set_postfix({")
    lines.append("            'loss': f'{loss.item():.4f}',")
    lines.append("            'acc': f'{100.*correct/total:.2f}%'")
    lines.append("        })")
    lines.append("    ")
    lines.append("    avg_loss = total_loss / len(loader)")
    lines.append("    accuracy = 100. * correct / total")
    lines.append("    ")
    lines.append("    return avg_loss, accuracy")
    lines.append("")
    lines.append("")
    lines.append("# 검증 함수")
    lines.append("def validate(model, loader, criterion):")
    lines.append("    \"\"\"모델 검증\"\"\"")
    lines.append("    model.eval()")
    lines.append("    total_loss = 0")
    lines.append("    correct = 0")
    lines.append("    total = 0")
    lines.append("    ")
    lines.append("    with torch.no_grad():")
    lines.append("        progress_bar = tqdm(loader, desc='Validation', ncols=100)")
    lines.append("        for data, target in progress_bar:")
    lines.append("            data, target = data.to(device), target.to(device)")
    lines.append("            ")
    lines.append("            output = model(data)")
    lines.append("            loss = criterion(output, target)")
    lines.append("            ")
    lines.append("            total_loss += loss.item()")
    lines.append("            pred = output.argmax(dim=1, keepdim=True)")
    lines.append("            correct += pred.eq(target.view_as(pred)).sum().item()")
    lines.append("            total += target.size(0)")
    lines.append("    ")
    lines.append("    avg_loss = total_loss / len(loader)")
    lines.append("    accuracy = 100. * correct / total")
    lines.append("    ")
    lines.append("    return avg_loss, accuracy")
    lines.append("")
    return "\n".join(lines)
